version: '3.9'
services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 81:80
      - 444:443
    networks:
      - app-test-inventario-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env    
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE: $DB_DATABASE
      - MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - app-test-inventario-network
  app:
    build: .
    restart: unless-stopped
    networks:
      - app-test-inventario-network
    volumes:
      - ./:/var/www
  node:
    image: node:lts-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: sh /var/www/node_start.sh
    depends_on:
      - app
   
networks:
  app-test-inventario-network:
    driver: bridge
volumes:
  dbdata:    